# Generated by Django 5.1.6 on 2025-02-26 21:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='time',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
