# Generated by Django 5.1.6 on 2025-02-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_journalentry_date_remove_journalentry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='visible',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
