# Generated by Django 5.1.6 on 2025-02-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journalentry_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='uid',
            field=models.UUIDField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
