# Generated by Django 5.1.6 on 2025-02-28 22:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_journalentry_uid_alter_journalentry_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='uid',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
